spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    root: INFO
