server:
  port: 8084

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

